version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: magsuite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/magsuite
      ALERT_EMAIL: alerts@example.com
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
