services:
  - type: web
    name: magsuite-backend
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      # - key: REDIS_URL  # Temporarily disabled for deploy
      #   sync: false
      - key: ACCESS_SECRET
        sync: false
      - key: REFRESH_SECRET
        sync: false
      - key: SSO_SECRET
        sync: false
      - key: API_KEY
        sync: false
      - key: FILE_ENCRYPTION_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: SUPABASE_CA_CERT
        sync: false
      - key: VAPID_PUBLIC
        sync: false
      - key: VAPID_PRIVATE
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: PGPOOL_MAX
        value: "20"
      - key: PG_IDLE_TIMEOUT_MS
        value: "30000"
      - key: PG_CONNECTION_TIMEOUT_MS
        value: "10000"
      # Deployment monitoring
      - key: LOG_LEVEL
        value: "info"
      - key: RENDER_API_KEY
        sync: false
      - key: RENDER_SERVICE_ID
        sync: false
      - key: APP_BASE_URL
        sync: false
