services:
  - type: web
    name: magsuite-backend
    env: docker
    plan: starter
    region: frankfurt
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ACCESS_SECRET
        sync: false
      - key: REFRESH_SECRET
        sync: false
      - key: SSO_SECRET
        sync: false
      - key: API_KEY
        sync: false
      - key: FILE_ENCRYPTION_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: DB_CA_CERT_B64
        sync: false
      - key: VAPID_PUBLIC
        sync: false
      - key: VAPID_PRIVATE
        sync: false
      - key: SENTRY_DSN
        sync: false
  - type: web
    name: magsuite-frontend
    env: static
    plan: starter
    region: frankfurt
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VAPID_PUBLIC
        sync: false
      - key: SENTRY_DSN
        sync: false
